version: '3.0'

services:
  nats:
    image: nats:latest
    command: "-js -m 5530 --config /root/config.yaml"
    ports:
      - "4222:4222"
      - "5530:5530"
    volumes:
      - ./nats.conf:/root/config.yaml