#
# Generated by @zondax/cli
#
-include Makefile.settings.mk

# Get all directories under cmd
CMDS=$(shell find cmd -type d)

default: build

build:
	@go build ./znats/...

mod-tidy:
	@go mod tidy

mod-update:
	@go get -u ./...

output/%: cmd/%
	mkdir -p $(dir $@)
	go build -o $@ ./$<

clean:
	go clean

gitclean:
	git clean -xfd
	git submodule foreach --recursive git clean -xfd

install_lint:
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin latest

check-modtidy:
	go mod tidy
	git diff --exit-code -- go.mod go.sum

lint:
	golangci-lint --version
	golangci-lint run

earthly:
	earthly +all

docker-bash:
	docker run --platform linux/amd64 -it zondax/${APP_NAME}:latest /bin/sh

docker-run:
	docker run --platform linux/amd64 -it zondax/${APP_NAME}:latest

########################################

zondax-update:
	@npx -y @zondax/cli@latest update

# include if exists
-include Makefile.local.mk

.PHONY: *
