name: Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  nats-server:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:latest
        ports:
          - "4222:4222"
          - "5530:5530"
        command: "-js -m 5530"
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build
        run: |
          make build
      - name: Unit tests
        run: |
          make test
      
